rekrutment-backend:
  build:
    context: ./rekrutment-backend
    dockerfile: Dockerfile
  image: rekrutment-backend:latest
  container_name: rekrutment-backend
  restart: unless-stopped
  working_dir: /var/www
  volumes:
    - ./rekrutment-backend:/var/www:cached
  ports:
    - "8001:80"   
  networks:
    - maharasa-net